### ISSUE TITLE
Failing to use Hardhat fork to impersonate accounts

### ISSUE THREAD

**Issue by golkir** [nomiclabs/hardhat#1071]
I used the example from the docs to impersonate an account on a forked network:

`await hre.network.provider.request({
  method: "hardhat_impersonateAccount",
  params: ["0x...."]}
)`
However, I get "Error: Returned error: unknown account". How should this be done correctly? Thanks

**Comment by fvictorio** [comment]
Hi @golkir, can you share your hardhat config, the command you are running in the terminal, and the relevant code (if there's something besides the snippet you shared)?

**Comment by fvictorio** [comment]
Closing this since we don't have enough information to look into it, but feel free to re-open if you can provide that info.

**Comment by platocrat** [comment]
@golkir @fvictorio 
After quickly converting my test script to TS, I noticed that the error is a result from `hre` not being globally available. 

The fix for me was importing just `hre` from hardhat:
```typescript
import hre from 'hardhat'
```

Then, you can impersonate an account like so (ignore the red underline under `before` since these test statements still compile as they should):
<img width="782" alt="Screen Shot 2021-01-17 at 12 09 53 PM" src="https://user-images.githubusercontent.com/37757724/104851824-e9878200-58bc-11eb-84a6-efebc65a7e51.png">

However, you'll have to covert all calls to `ethers.ETHERS_METHOD` to `hre.ethers.ETHERS_METHOD`, yet this did solve the issue for me. Let me know if this does/doesn't solve the issue for you.
