### ISSUE TITLE
How to extend HRE in TypeScript?

### ISSUE THREAD

**Issue by platocrat** [nomiclabs/hardhat#1143]
I really liked the idea of extending the HRE to add globally available random wallets as constants. However, implementing my desired logic in TypeScript appears to be a challenge. 

Here's what I have in my JS `hardhat.config.js`:
```js
/**
 * @notice For `hardhat.config.js`
 */
extendEnvironment(hre => {
  const randomWallet1 = hre.ethers.Wallet.createRandom()
  const randomWallet2 = hre.ethers.Wallet.createRandom()

  hre.randomWallet1 = randomWallet1
  hre.randomWallet2 = randomWallet2
})
```

I attempt to do the same in TypeScript. However, when I do, TypeScript complains that that `Property 'randomWallet1' does not exist on type 'HardhatRuntimeEnvironment'.ts` and I'm not sure how to get around this without just using the JS version.

### Edit:
* Corrected my mistake of duplicate code

**Comment by scnale** [comment]
When extending the `hre` in TypeScript, you need to extend the type `HardhatRuntimeEnvironment` itself too. I recommend you take a look at the [TS plugin boilerplate](https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/master/src/type-extensions.ts#L28) for a complete example on how to do so.

The gist of it is that you declare a `HardhatRuntimeEnvironment` interface that includes the new fields that you want to add so that it merges with the declaration from Hardhat. Note the `declare module "hardhat/types/runtime"` bit. That's necessary to merge with the Hardhat type declaration.

If you're not writing a plugin, you probably don't need to strictly follow the pattern shown in the TS plugin boilerplate.

**Comment by fvictorio** [comment]
@platocrat does that answers your question? Can we close this issue?

**Comment by platocrat** [comment]
> @platocrat does that answer your question? Can we close this issue?

Yep, you can close
