### ISSUE TITLE
Flatten does not consolidate licenses

### ISSUE THREAD

**Issue by aaronbuchwald** [nomiclabs/hardhat#1167]
Compilers produce warnings about the lack of licenses, so it's simplest to make sure that each file has a proper license at the top. However, when using hardhat flatten to produce a single contract that can be used on Remix, all of the licenses are left in tact in the new file. Although this seems to make the most sense, it produces an error when compiling within Remix, so it would probably be a better behavior if hardhat flatten consolidated the license lines into a single line to avoid the error.

**Comment by fvictorio** [comment]
This is a little harder than it seems. For example, what happens if there are incompatible licenses in the flattened contract?

If you are just using it for debugging in remix, I think the easiest solution is to just run a regex and remove all spdx comments. If you are on a UNIX system, this can be done with a one liner:

```
hh flatten | grep -v '// SPDX' > Flattened.sol
```

**Comment by fvictorio** [comment]
Closing this in favor of #1499.
