### ISSUE TITLE
eth_signTypedData incompatible with ethers _signTypedData

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#1199]
```ts
const permission = await ethers.provider
    .getSigner(ownerAddress)
    ._signTypedData(domain, types, value)
```

<img width="514" alt="image" src="https://user-images.githubusercontent.com/15959632/105643047-8d43d580-5e5b-11eb-9738-138b9a617079.png">

**Comment by ricmoo** [comment]
Does hard hat implement the `eth_signTypedData_v4` JSON-RPC method?

**Comment by thegostep** [comment]
Their docs show they support `eth_signTypedData` 

https://hardhat.org/hardhat-network/#supported-methods

**Comment by thegostep** [comment]
It seems like it uses `eth_signTypedData_v4` under the hood: https://github.com/nomiclabs/hardhat/blob/4532f4c742ca9d5055c1aa83346306354ebf1eed/packages/hardhat-core/src/internal/core/providers/accounts.ts#L72-L84

**Comment by ricmoo** [comment]
I don’t think that call is final yet, so they may need to at the very least make an alias to the `_v4` variant that other clients use. Otherwise it is too hard to tell what parameters to pass to the function. Ethers only supports the v4 parameters description and has no intention of supporting legacy versions of EIP-712...

Do you know what parameter description they are using for that call? Is it v4 compatible?

**Comment by ricmoo** [comment]
Their string matching against the method name is wrong though, as it is checking for `eth_signTypedData`. So that if condition is skipped.
