### ISSUE TITLE
console.log not support struct

### ISSUE THREAD

**Issue by PipsqueakH** [nomiclabs/hardhat#1286]
in hardhat/console.sol, the function console.log seems not support struct variable, will this be supported in the future?

**Comment by fvictorio** [comment]
Hi @PipsqueakH. This is not possible right now because the way `console.sol` is done, there are "hardcoded" methods for all the basic types (and some combinations). You can take a look at [`console.sol`](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/console.sol) to see what I mean.

There are some possible workaround around this, like parsing all `console.log` usages and generating the necessary code, but... it's hard, and honestly I don't think it's something we'll do soon.
