### ISSUE TITLE
Non-async way to have a list of accounts

### ISSUE THREAD

**Issue by sshmaxime** [nomiclabs/hardhat#1339]
Getting accounts is currently async. No problem with that at first sight unless you go deeper in mocha tests. If you need for some reasons to loop over your accounts in order to produce some tests it won't work properly:

```js
 let accounts;
  
 describe("test1", () => {
      before(async () => {
            accounts = await ethers.getSigners();
      })
      
      for (const recipient of [accounts[0], accounts[5]]) {
            context(recipient === owner ? 'for self' : 'for another account', async () => {
            for (let x = 0; x < 2; x++) {
                 describe(`base token (${x ? 'ETH' : 'ERC20'})`, () => {
                      it("blabla", async() => { ... })
                      it("blabla", async() => { ... })
                      it("blabla", async() => { ... })
                 }
            }
      }
 }

```

Will produce an error: `TypeError: Cannot read property '0' of undefined` and it is normal because as Mocha is passing through all describe (which is not async) to fetch each `it` tests, accounts is not yet initialized. For the notice, `before` and `beforeEach` hooks execute themselves after fetching all tests.

As of a solution, I'm proposing adding to hardhat a global variable, containing 10 default accounts like OpenZeppelin is doing in their [test-environement](https://github.com/OpenZeppelin/openzeppelin-test-environment/blob/master/src/accounts.ts) repo. Allowing the use of pre-defined accounts in a sync manner.

**Comment by fvictorio** [comment]
Two ideas for this:

1. Add the unlocked variables in a sync way, but only when you are using the in-process hardhat network
2. Add a helper that works like `describe` but that passes the accounts to the callback (similar to truffle's `contract`)

I don't particularly like either option.

Another idea is to distinguish between the accounts configured in the config (that, I think, we can get in a sync way) from the remote ones, and to expose the first with a sync method.

**Comment by sshmaxime** [comment]
Why not **just** having 10 ready to use accounts like OZ is doing ? it's the least complicated thing to do imo

**Comment by fvictorio** [comment]
Because then what's the behaviour when you connect to Rinkeby for example? If you have a mnemonic/list of private keys for that network, then (assuming there are sync accounts available), the correct thing would be to expose those.

When you connect to hardhat, you already have a mnemonic that gives you 20 accounts ready to use. So a consistent way of doing this is to just expose the accounts in the config. This is a problem for the `localhost` network connected to a local hardhat node (because in that case it relies on the remote accounts, and you can't get those in an async way), but in that case you either use the async ones or use the same mnemonic from the hardhat network in the `localhost` network.

I'm not that familiar with OZ, but I guess they can do that because they only run in an in-memory network, so testnets/other configured networks are not a problem, but they are in hardhat.

**Comment by sshmaxime** [comment]
Okay, got it. I would prefer avoiding having to install any kind of truffle related packages as it might be confusing/unclear. Do you think it would be doable to pass an `accounts` instance without needing the truffle plugin ? like so:

```js
describe("Escrow", (accounts) => {
     ...
}
```

**Comment by alcuadrado** [comment]
No, we can't do that in a general way. But you can copy the implementation of `contract` from the plugin. It's pretty small.

**Comment by fvictorio** [comment]
Hi @sshmaxime, any reason to re-open this? Is there something we can do on our side about this?

**Comment by sshmaxime** [comment]
Hey @fvictorio, I re-opened it thinking I had a genius idea. Started writing about it, but then realized that 1. it wouldn't have worked and 2. it wasn't a genius idea. And finally I forgot to closed it back. Sorry for that 🙈

**Comment by fvictorio** [comment]
Hahahaha I can relate to that.
