### ISSUE TITLE
Forked Hardhat Running Slowly When Uploading Data

### ISSUE THREAD

**Issue by mudgen** [nomiclabs/hardhat#1358]
Hello,
When executing a transaction on a forked network using Hardhat it often times out when executing a transaction with arguments containing a lot of data to store in the blockchain.  We are using Solidity 0.8.1.   Is there something we can do to get a forked hardhat network to executing data uploading/saving transactions faster?

**Comment by fvictorio** [comment]
@mudgen as the issue template says, this issue tracker is for bug reports and feature requests. For questions like these, use our [discord server](https://hardhat.org/discord)

**Comment by mudgen** [comment]
Hardhat forking isn't working for storing lots of data.  Isn't that a bug?

**Comment by alcuadrado** [comment]
Can you provide a way of reproducing it? That would be really helpful.

**Comment by mudgen** [comment]
Yes, I'm putting together a simple project that reproduces and shows the problem.  Can we reopen this issue?

**Comment by fvictorio** [comment]
@mudgen are you sure that this is not caused by what I mentioned in the discord server? The fact that you are writing data doesn't mean that Hardhat doesn't need to read stuff from the remote node. So the latency will still be there, and there isn't a lot we can do.

Anyway, if you are convinced this is a bug and have a minimal reproducible example, feel free to reopen.
