### ISSUE TITLE
Do not require presence of package.json in dependencies

### ISSUE THREAD

**Issue by ItsNickBarry** [nomiclabs/hardhat#1361]
Hardhat fails to import `.sol` files from a git repository dependency that does not have a `package.json`.

For example:
```bash
yarn add --dev https://github.com/abdk-consulting/abdk-libraries-solidity/
```

```solidity
import 'abdk-libraries-solidity/ABDKMath64x64.sol'
```

This import fails, unless a `package.json` is added to `node_modules/abdk-libraries-solidity`:
```json
{}
```

There is no obvious reason for this restriction, and it should be removed if possible.

**Comment by alcuadrado** [comment]
This is really interesting, @ItsNickBarry. 

I'm not sure if we can remove that limitation, as wee need some way to have a way of understand if `require.resolve` failed because the library wasn't installed, or the file isn't present. We do this by first reading its `package.json`, and resolving from there. 

Also, as Hardhat is case sensitive, we need to be able to get the root of the library, and we also do that this way.

Note though that npm doesn't let you install a github repo if it doesn't have a `pacakge.json`.

**Comment by ItsNickBarry** [comment]
It turns out that this particular library is published on NPM, though there's no `package.json` in the git repository.  Maybe the best solution to this issues is for package authors to properly document and publish their code.

**Comment by fvictorio** [comment]
I'm not sure what to do about this issue. @ItsNickBarry is there something we can do on our side? If so, please let us know and re-open it.

**Comment by ItsNickBarry** [comment]
An improved error message for this special case would be useful, but probably not worth maintaining.  In any case, this issue is no longer a problem for me so I don't particularly care.

**Comment by fvictorio** [comment]
> It turns out that this particular library is published on NPM, though there's no package.json in the git repository. 

I just installed it and a `package.json` is there. Maybe they don't have one in their repo, but I'm pretty sure you need one before you `npm publish`.

**Comment by ItsNickBarry** [comment]
Yes, this particular library has an NPM package with `package.json`, but it's not in the repository.  They don't advertise the existence of the package, so I at first installed it using the git repository.
