### ISSUE TITLE
Configure provider to avoid disk I/O

### ISSUE THREAD

**Issue by barakman** [nomiclabs/hardhat#1478]
**Feature Request**:

Allow the user to configure the provider to avoid disk I/O.

This is typically possible when the provider is ganache, by setting [the `db` property](https://github.com/trufflesuite/ganache-core/tree/master#options) to `memdown()`.

In Truffle, for example, this can be achieved via the configuration file:
```
const memdown = require('memdown');

module.exports = {
    networks: {
        networkName: {
            provider: ganache.provider({
                db: memdown(),
                ...
            }),
            ...
        },
        ...
    },
    ...
};
```

I tried to configure this in HardHat via the `paths.cache` [configuration option](https://hardhat.org/config/#available-config-options), but HardHat expects a string for this property, thus throwing an exception at [config-validation.ts](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/core/config/config-validation.ts#L24).

I suppose that there might be way to do this by sending an asynchronous request to the provider itself, but executing such a request from HardHat's configuration file is not really an option.

Thanks

**Comment by alcuadrado** [comment]
I don't think we ever used a disk-based db, but I may be getting this wrongly. Do you know where/how this happen?

**Comment by barakman** [comment]
@alcuadrado : Wow, thank you for the incredibly fast response!

Note that I've removed the 'reduce process memory size' incentive, as I've realized that it wouldn't necessarily achieve that.

We are currently experiencing `heap out of memory` when executing `hardhat coverage`.

Changing it to `NODE_OPTIONS='--max-old-space-size=SomeSize' hardhat coverage` doesn't resolve the problem.

In fact, `db: memdown()` might actually make this problem worse, who knows...

But regardless of our current problem, having this option would be a great benefit IMO, as it may significantly increase HH performance.

**Comment by alcuadrado** [comment]
There's not such an option in Hardhat, I don't even know what it does in Ganache tbh. We just don't use that db thing. Everything is already in-memory. 

Right now we don't use merkle-patricia-tree either, as it has a bug.

Is the OOM error immediate, or after running multiple tests?

**Comment by barakman** [comment]
@alcuadrado: The OOM error occurs after running for several hours.

It is not something new BTW, I do know that `solidity-coverage` suffers this problem on large test suites.

In the distant past (solidity-coverage v0.5.x), I have managed to devise a fix for that within the package source code (which I have applied using a script executed immediately after `npm install`).

But solidity-coverage is now at v0.7.x, and in any case, I don't feel that doing these "hot fixes" is the right way to solve such problems.

**Comment by alcuadrado** [comment]
I suspect it's the coverage that's using too much memory. @cgewecke does this sounds familiar to you?

BTW, several hours?! 😱

**Comment by cgewecke** [comment]
@alcuadrado 

I've been seeing HardhatEVM OOM periodically when I launch it once in a separate tab and repeatedly run test suites with the same client instance. I don't believe the issue is coverage specific and have just assumed that if everything's in memory...why wouldn't it eventually run out? 

@barakman Since it's hours, perhaps you could look at partitioning the suite into smaller pieces? There are some recipes for parallelizing coverage in CI and merging the reports for each job in a final step here: 

+ [Synthetix (codecov)][1]
+ [SetProtocol-V2 (coveralls)][2]

[1]: https://github.com/Synthetixio/synthetix/pull/1275
[2]: https://github.com/SetProtocol/set-protocol-v2/blob/aa894d7aef2f3db0819b05f06d18e7b3d851b25b/.circleci/config.yml#L60-L121

**Comment by barakman** [comment]
@alcuadrado:
It's pretty logical to me that this is a coverage issue, since `hardhat test` completes successfully and `hardhat coverage` doesn't.
Several hours - yes.
Not only do we have a very large test-suite, but we also refrain from using `before`, i.e., we use `beforeEach` only, and you can imagine how longer the execution subsequently takes.
That being said, execution time doesn't necessarily impact the memory consumption of the process (in fact, it most likely doesn't).
We have in our code many cases of `it` clauses and even `describe` clauses inside `for` loops.
These loops are "unrolled" (by mocha?) before the tests start running, and I suspect that this might increase the process memory consumption significantly.

@cgewecke:
Thank you, I will look into that.
BTW, you may recall that back in v0.5.x, I used to apply a patch on your source code to reduce memory consumption.
It is described in one of the (now closed I suppose) issues on your GitHub.
It was around the area where you used to save the pre and post events inside an in-memory table, which would technically become huge when a large amount of Solidity code was being tested (or a large number of `it` clauses were being executed, not sure which one is it).
I suppose that you no longer maintain such a table in memory, correct?
If it helps, some of the code that I tweaked back then was in and around function `generate(events, pathPrefix)` and function `processEvent(line)`.

Thank you both :)

**Comment by fvictorio** [comment]
Hey @barakman, thanks for all the details. I'm curious about what we can do about this. At the very least, it would be interesting to know if hardhat OOMs in large test suites (without coverage), but apparently it doesn't in your case?

And if the problem is when `solidity-coverage` is used, it would still be very useful to know if there's something we can do. For example, I think it's completely possible that the problem is actually in hardhat, but that it only happens after `solidity-coverage` instruments the code.

@barakman if your repo is public and the way to reproduce this is to just run the tests with coverage enabled, could you please share it with us?

**Comment by barakman** [comment]
@fvictorio : Thank you for your reply.
We were able to solve this by increasing `max-old-space-size` to 8192, i.e:
```
"NODE_OPTIONS='--max-old-space-size=8192' hardhat coverage
```
Thanks again for your help :)
