### ISSUE TITLE
CI tests with False negative

### ISSUE THREAD

**Issue by akiraplusplus** [nomiclabs/hardhat#1496]
Having frequent false negatives, specially around fork tests that use Alchemy. We should look into this since it's annoying and sometimes delays the merging of a PR until tests are re-run.

**Comment by fvictorio** [comment]
Hi @akiraplusplus. Thanks for submitting this. We are well aware of this problem and have tried to fix it a couple of times, but without success. There are some things we can try, but they mean making huge changes to our test structure, and/or changing the CI used (we are considering CircleCI).

I'll keep this open anyway because it makes sense to have it explicitly acknowledged.

**Comment by akiraplusplus** [comment]
Ok, great, It was fixed on my end, and going to close at this time. Thx!

**Comment by fvictorio** [comment]
Oh, I thought you meant _our_ tests (which also have false negatives because of Alchemy). How did you solve this in your project?
