### ISSUE TITLE
Handle base fee of the first block after the genesis correctly

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1614]
- The base fee of first block after genesis is tricky
    - The base fee is reduced because the genesis block has 0 gas used. This is probably not what users want when they set an initial base fee.

**Comment by alcuadrado** [comment]
@fvictorio what if we set the initial base fee to the blocks 0 (i.e. genesis) and 1?

**Comment by fvictorio** [comment]
That might make more sense from a user perspective, but it would mean that the network would start with an invalid state transition, wouldn't it? I think it's a fine trade-off, just something to keep in mind.

A more involved alternative: set the base fee of block 0 to a value X such that X becomes the value selected by the user after one empty block.

**Comment by alcuadrado** [comment]
I also thought about that alternative, but I don't think that's always possible because of rounding errors. So that would also lead to an invalid state transition.

**Comment by fvictorio** [comment]
I'm wondering if it wouldn't be better to leave it like that, and have a valid transition. If what the user really wants is to configure the next base fee, then they can use the `hardhat_setNextBaseFee` method (or however we call them).

If we set the base fee in the 0 and 1 blocks, then users that want the "correct" behavior wouldn't have a way to do it.

This should be very well documented though, otherwise users are going to get confused.

**Comment by alcuadrado** [comment]
Yeah, I think that makes sense. It's more correct.

What about forking? I'd say that `initialBaseFee` is the `baseFee` of the first local block. WDYT?
