### ISSUE TITLE
Possible bug around CREATE2

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1626]
Reproduction repo: https://github.com/Shadowfiend/hardhat-create2-bug

I took an initial look into this and it seems indeed like a bug, but maybe I'm missing something.

Thanks @Shadowfiend for letting us know about this and making a superb reproduction example!

Some things I've already tried:
- Using the same address than waffle provider initializes (it doesn't make sense anyway, the first account is only used to fund the account that deploys the factory).
- Using `ethers.provider` instead of `waffle.provider`

**Comment by Shadowfiend** [comment]
Okay, so I dug some more here. The issue is that the way the EIP-2470 `SingletonFactory` works will produce a successful transaction even if the CREATE2 fails, because it's just a direct call to CREATE2, and CREATE2 is defined as returning 0 but not throwing/reverting on failure, which sucks 🙃

At its core, what we're seeing is an out-of-gas for the CREATE2 call. In fact, the gas limit set when using the Hardhat provider is 68538, whereas with the waffle `MockProvider` it's 68655. Sure enough, passing an explicit `gasLimit: 68655` in both cases makes both pass; as such, this means the likely issue is in gas estimation here.

From a quick skim of the gas estimation code, the fact that the CREATE2 call won't revert means the initial estimate correction will miscategorize the initial estimate as correct, and even if it wasn't marked correct it would be considered correct during the binary search:

https://github.com/nomiclabs/hardhat/blob/7637c942e9ab7b424cab08a58306e13e8feaf32e/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L1676-L1678

https://github.com/nomiclabs/hardhat/blob/7637c942e9ab7b424cab08a58306e13e8feaf32e/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L1748-L1756

In both of these cases the call has no error---but has a different effect than what was intended.

The context does, however, have the necessary information to decide this more appropriately: `result.execResult` here carries `returnValue`, which varies between the two. I'm not sure if it's the right thing to have the estimate correction code pay attention to this, or if it's better to dig into why the initial estimation differs---both may be outside the scope of what I can currently do, however.

Last datapoint: although in this minimized example, the difference in estimated vs actual gas is a mere 17 gas, in the more complex use case that triggered this bug we're looking at a much larger difference of 104504—unclear what the difference is, other than that the deployment bytes are much larger (2880 vs 92).

**Comment by fvictorio** [comment]
Wow, that's very, very helpful. Thanks a lot for sharing @Shadowfiend!

**Comment by paulrberg** [comment]
Just bumped into this as well. More data points:

- This bug does not occur if the compiler optimizer is disabled
- The bug does not occur if I check if the address returned by CREATE2, and revert if it is zero

Here's my function:

```sol
function clone(bytes32 salt) internal returns (address payable proxy) {
    bytes20 impl = bytes20(address(implementation));
    assembly {
        let bytecode := mload(0x40)
        mstore(bytecode, 0x3d602d80600a3d3981f3363d3d373d3d3d363d73000000000000000000000000)
        mstore(add(bytecode, 0x14), impl)
        mstore(add(bytecode, 0x28), 0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000)
        proxy := create2(0, bytecode, 0x37, salt)
    }
}
```

Which was called by a child contract that exposed the `clone` function:

```sol
function __godMode_clone(bytes32 salt) external returns (address payable proxy) {
    proxy = clone(salt);
}
```

Luckily, in my case, I was able to fix this by checking the proxy address:

```sol
function clone(bytes32 salt) internal returns (address payable proxy) {
    // ...
    if (proxy == address(0)) {
        revert PRBProxyFactory__CloneFailed(salt);
    }
}
```

**Comment by feuGeneA** [comment]
@alcuadrado and I worked together on this.  We reduced the reproduction and showed that there is no problem in the Waffle or Ethers layers, and that the problem must be either in Hardhat Network or in ethereumjs/vm.  To show this, we translated the wonderful reproduction repository given in this issue into the following simple sequence of RPC calls:

```javascript
const hre = require("hardhat");

const myMain = async function() {
    // fund the address that will deploy the transaction:
    await hre.network.provider.request({
        "method": "eth_sendRawTransaction",
        "params": [
            "0x02f874827a6980849502f90085010c388d0082520994bb6e024b9cffacb947a71991e386681b1cd1477d8757c084e5f3c00080c001a0a3d1ec8375a6de1b1243026b36e5358f4bd2fa7a89c40f9b097a3c297db03267a055910d1cb33e5c9a0c414e582dbdcb25ebcce8d565455fe1adaa0b63851dbac7"
        ]
    })
    // execute singletonFactoryDeploymentTx that's hardcoded into eip-2470
    await hre.network.provider.request({
        "method": "eth_sendRawTransaction",
        "params": [
            "0xf9016c8085174876e8008303c4d88080b90154608060405234801561001057600080fd5b50610134806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80634af63f0214602d575b600080fd5b60cf60048036036040811015604157600080fd5b810190602081018135640100000000811115605b57600080fd5b820183602082011115606c57600080fd5b80359060200191846001830284011164010000000083111715608d57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600092019190915250929550509135925060eb915050565b604080516001600160a01b039092168252519081900360200190f35b6000818351602085016000f5939250505056fea26469706673582212206b44f8a82cb6b156bfcc3dc6aadd6df4eefd204bc928a4397fd15dacf6d5320564736f6c634300060200331b83247000822470"
        ]
    })
    // deploy our custom contract using the factory that was just deployed above
    await hre.network.provider.request({
        "method": "eth_sendRawTransaction",
        "params": [
            "0x02f90132827a6901849502f90084f04caa9a83010bba94ce0042b868300000d44a59004da54a005ffdcf9f80b8c44af63f020000000000000000000000000000000000000000000000000000000000000040c02b59f772cb23a75b6ffb9f7602ba25fdd5d8e75ad88efcc013fec2c63b0895000000000000000000000000000000000000000000000000000000000000005c6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220d7820c7c7f73919e8d23d9ac00f2a8282d3b057807f960372a8b61b956c3c73264736f6c6343000800003300000000c001a0242ed16b22d01a1b49735491223b2a978f6d13a219d6554ff12b02a83d353a2da06dc55ff7989e7956883e2a384518137837a65bf952da41cfd0a4f2c9878169a8"
        ]
    })
    // make sure there's code deployed at the address
    console.log(await hre.network.provider.request({
        "method": "eth_getCode",
        "params": [
            "0xb37f3d9239733da8c83f548a79916384181fa427",
            "latest"
        ]
    }))
}

myMain()
```

and then ran that via `yarn hardhat run script.js`, which can be run in an empty hardhat project.

**Comment by feuGeneA** [comment]
Had another discussion with @alcuadrado about this.

We verified that using the same gas limit across all of (Hardhat Network, ganache *and* geth) results in the same behavior.  So we don't think there is an issue in Hardhat Network's execution of `create2`.

The only difference that we can see is that ganache gives a higher gas estimation whereas Hardhat Network and geth give a lower one.  Both Hardhat Network and geth fail to execute the test correctly when their gas estimation is used (rather than using a hardcoded value).  It's known that Hardhat Network and geth estimate gas in a similar way; and that ganache uses alternative methods.

It seems to us that the `SingletonFactory`'s `deploy` method, as depicted in EIP-2470, is not handling any error result from the `create2` opcode execution.  Because of that, both Hardhat Network and geth return a lower estimation than what's needed.  @paulrberg this is related the scenario you encountered; you should always validate the return of `create2`, unlike that implementation in EIP-2470.  Because of this deficiency in the EIP-2470 implementation, we feel this is not an issue in Hardhat, so we're closing this issue.

Note also that in the test provided by @Shadowfiend , the assertion comparing of the destination address generated via `callStatic` to the address computed by `getCreate2Address` will always pass because the gas limit for `eth_call` (used by `callStatic`) is very high, much higher than what the gas estimation returns.

**Comment by feuGeneA** [comment]
Here's an example of error checking that could/should be done for the `create2` opcode: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/296223f876924da18b5aadd3343f4e2324f6176c/contracts/utils/Create2.sol#L40

**Comment by Shadowfiend** [comment]
Sweet, thanks for confirming my suspicions above so thoroughly!

> It's known that Hardhat Network and geth estimate gas in a similar way; and that ganache uses alternative methods.

This is something I didn't know, and explains that estimate discrepancy for sure! Did you happen to see if there was any easy adjustment that could help this estimate be more correct in HardHat Network, and if so a process to propose and implement such an adjustment?

**Comment by alcuadrado** [comment]
We implemented `eth_estimateGas` to closely mimic what geth does, so that testing with Hardhat Network is closer to running against mainnet. This is doing a binary search of a somewhat tight upper bound of the required gas limit. This is slow, as you need to execute the same tx multiple times, but it's exactly what geth does.

Ganache, on the contrary, executes the tx onces and tries to compute an upper bound based on a single execution trace. This is faster, but can lead to pretty different results when compared to geth, as the gas limit itself alters the execution of the tx.

**Comment by Shadowfiend** [comment]
Awesome, thanks for the detailed explanation!
