### ISSUE TITLE
hyperledger intergration

### ISSUE THREAD

**Issue by Shrikee** [nomiclabs/hardhat#1674]
Hey guys. Trying to migrate from Truffle to hardhat but got an issue: 
I'm running the hyperledger-fabric evm. When trying to deploy the contract to the network I recieve this kind of error: 
`ProviderError: rpc: can't find service "web3.ClientVersion`
Seems like hh is trying to query the rpc with this:
` {"jsonrpc":"2.0","method":"web3_clientVersion","id":1}`
And rpc response is 
`rpc: can't find service "web3.ClientVersion"`

How this could be resolved? 

ps
In truffle you just set the network type to 
`type: "fabric-evm"`

**Comment by fvictorio** [comment]
We don't have anything built-in related to hyperledger, but Hardhat should work with any EVM compatible network (it currently works with networks like Polygon and BSC without us having to do anything special). I'm not sure where that `web3_clientVersion` request comes from, but my guess is that you are using a library that queries that method. Maybe you can enable it somehow in the node you are using?

I'm going to close this because I don't think there's something we can do on our side. If hyperledger needs some non-standard things to work, my guess is that a "hardhat-hyperledger" community plugin could be created. If someone is interested in doing that, please join [our Discord server](https://hardhat.org/discord) and we can try to help in the `#plugin-development` channel.
