### ISSUE TITLE
Can't install packages for Hardhat project

### ISSUE THREAD

**Issue by lakshh07** [nomiclabs/hardhat#1724]
I wanted to create a project using Hardhat environment. I've tried following the https://hardhat.org/getting-started/ tutorial from their side. In there, we have a TIP to install all required packages. Unfortunately when I run `npm install --save-dev @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers` first I can see a lot of warnings about deprecated packages and then

```
npm ERR! code ENOENT`
npm ERR! syscall lstat
npm ERR! path git`
npm ERR! errno -4058`
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(path)
```

I've tried installing `ethereum-waffle` with specific version selected etc. it always ends with the same error.

Do you know how to overcome it? Why so many packages are deprecated during install? Is this getting-started outdated and I should start `hardhat` project in some other way?

**Comment by fvictorio** [comment]
This seems like something related to your machine. Maybe you are using an old version of npm/yarn, maybe there's something wrong with your npm/yarn cache, maybe it's something else entirely, but I'm pretty sure it's not related to Hardhat itself.

> Is this getting-started outdated and I should start `hardhat` project in some other way?

No, it's not outdated and it should work.

Closing this since I don't think there's anything we can do on our side. Please use [our Discord server](https://hardhat.org/discord) if you have more questions.

**Comment by fvictorio** [comment]
@aftermathdigital mentioned that this happens when `git` is not installed. Not sure if that's the case here, just mentioning it in case someone ends up reading this issue after googling that error message.
