### ISSUE TITLE
Conflict between HH208 and HH310 errors

### ISSUE THREAD

**Issue by bugduino** [nomiclabs/hardhat#2034]
Hi,
I'm trying to give tasks parameters some nice names, but it seems that there is a conflict and only lowercase param names can be used.

Some example I encountered with hardhat v2.6.8
``` 
npx harhdhat fake --long-name-param "foo"
```
gives the error 
```Error HH208: Invalid param name long-name-param in task fake. Param names must be camelCase.```

while this
``` 
npx harhdhat fake --longNameParam "foo"
```
gives the error 
```Error HH310: Invalid param --longNameParam. Command line params must be lowercase.```

Is there a way to use such param name format?

**Comment by fvictorio** [comment]
You need to define your task in camelCase, but you use it in the terminal as kebab-case:

```js
task("fake")
  .addParam("longNameParam")
  .setAction(async (taskArgs, hre) => {
    // do stuff
  });
```

```
npx hardhat fake --long-name-param value
```

The reason for this is that you can then use the param as `taskArgs.longNameParam` instead of `taskArgs["long-name-param"]`, but it's understandably confusing at first.

I hope this helps. I you have more questions, please use [our Discord server](https://hardhat.org/discord) or [GitHub's discussions](https://github.com/nomiclabs/hardhat/discussions).
