### ISSUE TITLE
[ Suggestion ] A build like Docker

### ISSUE THREAD

**Issue by ghost** [nomiclabs/hardhat#2095]
For Hardhat, the idea of ​​an environment where anyone can create and share their own build and boilerplate sounds good.
example **hardhub**

```bash

hardhat pull <package-name>

```

**Comment by feuGeneA** [comment]
For Docker, a system like that is important because the built artifacts can be both massive and extremely time consuming to produce.  Hardhat "builds" are just compiled Solidity, and it's easy enough to clone a repo of source code and then compile it oneself, so it's not likely that we would consider implementing this.  If you strongly disagree, please feel free to re-open this Issue and make your case.  Thanks for your engagement.
