### ISSUE TITLE
evm_mine allow to specify number of blocks to mine

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#2108]
currently in order to skip x block, you have to call evm_mine x times

it would be great to have the ability to specify the number of blocks to mine

In ganache there is support for that : https://trufflesuite.github.io/ganache/#evm_mine

**Comment by fvictorio** [comment]
Hey Ronan, we are already tracking this in https://github.com/nomiclabs/hardhat/issues/1112 (which is our most upvoted issue!)

We are working on this and I guess we'll release it in the coming weeks. It's taking some time because we want something that works in constant time (ganache's implementation is a loop, IIRC) but that simulates as well as possible what would happen if you mined the same number of blocks manually (like the miner rewards, the state trie, etc), and this presents some difficulties.

**Comment by wighawag** [comment]
Sorry, should have checked if there was previous issue, Glad it is on the roadmap and that you continue thriving for quality :)
