### ISSUE TITLE
Hardhat verify does not set HARDHAT_NETWORK environment variable.

### ISSUE THREAD

**Issue by jdiegosierra** [nomiclabs/hardhat#2301]
I want to access process.env.HARDHAT_NETWORK in hardhat.config file. For example for load some environment variables:

```
dotenv.config({
  path: `${__dirname}/.env.${process.env.HARDHAT_NETWORK}`,
});
```
When I run `npx hardhat run --network development` all is OK, but when I use `npx hardhat verify --network development`, process.env.HARDHAT_NETWORK is undefined

**Comment by alcuadrado** [comment]
Hey @jdiegosierra,

Hardhat never sets env variables. What would you expect it to do in that case?

**Comment by jdiegosierra** [comment]
Then, who sets `HARDHAT_NETWORK` when running  `npx hardhat run --network development`? Because I can see this variable setted...

**Comment by alcuadrado** [comment]
I see @jdiegosierra! `hardhat run` opens a subprocess of node, where your script is run. In that case Hardhat's cli communicate some params to the subprocess using env variables.

**Comment by msmyers** [comment]
How would one do what he is asking? How would one detect which network is active (or will be active) when `hardhat.config.ts` is imported?

Example use-case: I want to print debug information about the current network config while I'm assembling it.

**Comment by fvictorio** [comment]
@msmyers sadly that is a limitation of Hardhat's architecture right now. The arguments are not available in the config because we need to resolve the config before knowing all the kinds of arguments that will exist.

We've discussed exposing only the "global" arguments in the config (`--network` being the most useful one) as a possible solution for this, but we haven't done that yet.
