### ISSUE TITLE
Compile of imported contracts are duplicated if filename casing doesn't match

### ISSUE THREAD

**Issue by tmilar** [nomiclabs/hardhat#538]
When importing a contract file named `MyContract.sol` from `A.sol` like this:
```
// MyContract.sol
contract MyContract {
}
```
```
// A.sol
import './mycontract.sol'
contract A { 
}
```
The `npx buidler compile` task not only does not fail, it also compiles the whole contract file _two times_, apparently one as './mycontract.sol' and the other as './MyContract.sol'.
```
Compiling...
Compiled 3 contracts succesfully
```
Now, when the imported file casing is correct, the file is only compiled 1 time: 
```
// A.sol
import ./MyContract.sol'
contract A { 
}
```
```
Compiling...
Compiled 2 contract succesfully
```
I think when the naming of an imported file doesn't exactly match, it would be expected that the compilation would fail, or at least doesn't do it double the times.

The reason I believe it to be duplicated as well, is that when the imported file contains more than one contract defined, they are also duplicated. For example:
```
// MyContract.sol
contract MyContract1 {
}
contract MyContract2 {
}
contract MyContract3 {
}
```
```
// A.sol
import './mycontract.sol'
contract A { 
}
```
Results in `7 contracts compiled succesfully` instead of the expected 4 when imported properly.

Current environment:
Win10
Buidler v1.3.1
Node v10.16.0

**Comment by cameel** [comment]
This looks like a discrepancy between the way compiler tracks files and the way Hardhat finds them on a case-insensitive filesystem.

For the compiler file names are always case-sensitive, even if you're on a case-insensitive filesystem. If you have one file that imports `mycontract.sol` and another that imports `MyContract.sol`, the compiler will see it as two different files and compile it twice. After all, the source code does not have to come from actual files - you can just as well provide JSON input where these two keys are associated with completely different source code.

I think that the issue here is that on a case-insensitive filesystem Hardhat finds `MyContract.sol` on disk when you import `mycontract.sol` and gives it to the compiler under the name `mycontract.sol`. Then it also notices that there's `MyContract.sol` on disk and it's not in the input (it's not equal to `mycontract.sol` after all) so it adds it again.

It should not break anything unless you have files with names that differ only with case but then you would not be able to store that project on a case-insensitive FS anyway. It does lead to contracts being compiled unnecessarily though.

BTW, I'd suggest not relying on the fact that `mycontract.sol` happens work for you. Please use the exact case your files have on disk. Otherwise your project won't compile if you move it to a case-sensitive FS. This might make it impossible to pass bytecode verification.

**Comment by fvictorio** [comment]
Thanks @tmilar for reporting this and thanks @cameel for the explanation. I agree that Hardhat should fail early in this case.

**Comment by alcuadrado** [comment]
That's exactly what was going on, @cameel :)

This issue was present in Buidler, but not in Hardhat. If you run the example in the original message, you get this error:

```
% hh compile
Error HH409: Trying to import ./mycontract.sol from contracts/A.sol, but it has an incorrect casing.

For more info go to https://hardhat.org/HH409 or run Hardhat with --show-stack-traces
```

These casing issues may be something you want to mention in the docs, @cameel, as it's really easy to accidentally ignore them.

**Comment by cameel** [comment]
Great!

> These casing issues may be something you want to mention in the docs, @cameel, as it's really easy to accidentally ignore them.

Right and that's not the only gotcha related to paths. I actually have a big docs update in the works that describes how the paths work in the compiler, including tons of examples of weird situations that can bite you: https://github.com/ethereum/solidity/pull/11263. It's already written but it ended up being pretty long so we decided to split it - only a concise description listing all the rules will go into the docs and the text expanding on how they interact creating potentially unintuitive corner cases, including examples of potential problems will be a blog post.

I do mention there that paths are platform specific, but not this particular detail. I'll add it.

My ultimate goal is to also remove some of these gotchas and reduce complexity around paths and mports but this will unfortunately require some breaking changes. For example I think that the compiler should report an error (or at least a warning) if it finds a file with a different case on a case-insensitive filesystem because that's not portable and will bite the user eventually even if it works on his system. If Hardhat is already reporting an error for this then it's all the more reason to change it.
