### ISSUE TITLE
Try to auto-resolve etherscan api endpoint from network name

### ISSUE THREAD

**Issue by paxthemax** [nomiclabs/hardhat#583]
Currently, when configuring `buidler-etherscan` plugin, the network api endpoint is a mandatory parameter:

```
  etherscan: {
    url: "https://api-rinkeby.etherscan.io/api",
    apiKey: ETHERSCAN_API_KEY,
  }
```

I propose the following:
Make the `url` parameter _optional_, and try to resolve the network (eg. ropsten, rinkeby etc.) from the _name_ of the network in the BRE. 

A call to:
`yarn buidler verify-contract --name Example --network rinkeby --address 0x...`

Would use the apropriate rinkeby url.

Providing the url in config (or potentially as a task argument) would override the default.

**Comment by fvictorio** [comment]
This is related to something I think could be improved for the etherscan plugin. I think the `url` field should accept a map of networks to urls, something like:

```
url: string | {[network: string]: string}
```

If you pass a string, the same URL is used for all networks (which maybe doesn't make sense, but it would make it easier to use when you only care for one network). If not, the url is taken from the map using the selected network.

If this is implemented, then your issue is fixed by simply using a reasonable default value for the url.

**Comment by alcuadrado** [comment]
This has already been implemented. Thanks, @paxthemax.
