### ISSUE TITLE
old artifacts should be deleted when compilation occurs

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#727]
Currently old artifact remains in the artifact folder even if the new compilation does not include them (source file deleted)

This can cause problem for tool that need to for example extract the metadata out of the solc-ouput

Indeed, they have no way to know if the artifact is newly compiled or not and when attempting to get the metadata it fails as the old contract is not included in the solc-output

This problem would not exist if the artifact contains the metadata (but this is not unique to metadata, as there might be other use case for looking at the solc-output_

**Comment by gitpusha** [comment]
Hi @wighawag . One of my concerns would be that I might want to compile some contracts with a different compiler setting and then store their artifacts in `artifacts/` in order for buidler-deploy to also look at them.

However, this can be handled instead with the `imports` setting, correct? So that I still have the option to use pre-compiles with buidler-deploy.

**Comment by wighawag** [comment]
yes, import is intended for that, but I actually need to add the ability to add metadata to these "artifacts" in the import folder, going to add that

An altermative to delete would be to save a hash of the solc-input so that tool can check if the belong to same compilation unit.

I think delete is simpler

**Comment by alcuadrado** [comment]
> An altermative to delete would be to save a hash of the solc-input so that tool can check if the belong to same compilation unit.

This will be supported in the new compilation pipeline we are working on.

**Comment by fvictorio** [comment]
Supported in the new compilation pipeline.
